POST http://localhost:3001/api/children
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvaW5lbi50eW9udGVraWphQGVtYWlsLmZpIiwiaWQiOiI2NGVlZGUyNjQ0MTQ5M2QwYzczN2I0N2QiLCJpYXQiOjE3MDA3MzA1OTAsImV4cCI6MTcwMDczNDE5MH0.YYxoqlE_VKjb2PIv0p57RzCbEkilTj4Os41ALFAz9ow"

{
        "name": "Kikka Forbes",
        "born": "05.11.2021",
        "parents": ["Caroline Forbes-Kirk"],
        "monthly_maxtime": "150",
        "daycare": "64f7f226d5121cd7a7d50887",
        "group": "64e70878d2ec240813742adf"
}
