DELETE http://localhost:3001/api/children/6507f8a77ee5794652673730/caretimes/653f9167b6ee311ac7c4801a
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbm5pbi5zYWhrb3Bvc3RpQGVtYWlsLmNvbSIsImlkIjoiNjRmODA5YzRjZTJiYjI4YzM5MWU4MDRhIiwiaWF0IjoxNjk4NjY4MzYyLCJleHAiOjE2OTg2NzE5NjJ9.NVKpac0Dj_ID_qZN3B_EXrjd0aXZ_9c3UNjp3kMGLYg



# GET http://localhost:3001/api/children/6507f8a77ee5794652673730
# content-type: application/json
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbm5pbi5zYWhrb3Bvc3RpQGVtYWlsLmNvbSIsImlkIjoiNjRmODA5YzRjZTJiYjI4YzM5MWU4MDRhIiwiaWF0IjoxNjk4NjY4MzYyLCJleHAiOjE2OTg2NzE5NjJ9.NVKpac0Dj_ID_qZN3B_EXrjd0aXZ_9c3UNjp3kMGLYg

